#!/usr/bin/env bash
# scripts/graph/test_memory_loop.sh
#
# Offline guard tests for the graph memory loop: pins that graph/memory/
# holds committed (non-ignored) reflection entries with valid frontmatter,
# that graph/reflections/LESSONS.md is produced by `graphify reflect`, that
# the weekly-playbook workflow wires the reflect step, and that the Ralph
# harness instructions (PROMPT.md, chief-architect, code-review-orchestrator,
# adepthood-constraints, the graph skill) all tell agents to save memory
# entries. Also runs a live graphify reflect round-trip when the CLI is on
# PATH, entirely inside a throwaway mktemp fixture.
#
# Run:  bash scripts/graph/test_memory_loop.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MEMORY_DIR="$ROOT/graph/memory"
LESSONS="$ROOT/graph/reflections/LESSONS.md"
WORKFLOW="$ROOT/.github/workflows/weekly-playbook.yml"
REFLECT_MARKER="Auto-generated by \`graphify reflect\`"

PASS=0
FAIL=0
ok()  { PASS=$((PASS + 1)); printf '  ok  - %s\n' "$1"; }
bad() { FAIL=$((FAIL + 1)); printf 'FAIL  - %s\n' "$1"; }
check_contains() { # check_contains <desc> <file> <needle>
  if grep -qF -- "$3" "$2"; then ok "$1"; else bad "$1 (missing '$3' in $2)"; fi
}

# --- group 1: graph/memory/ has at least one committed entry -----------------
# while-read instead of mapfile so macOS system bash 3.2 can run this too.
MEMORY_ENTRIES=()
if [[ -d "$MEMORY_DIR" ]]; then
  while IFS= read -r f; do MEMORY_ENTRIES+=("$f"); done \
    < <(find "$MEMORY_DIR" -maxdepth 1 -name '*.md' | sort)
fi
if [[ "${#MEMORY_ENTRIES[@]}" -gt 0 ]]; then
  ok "graph/memory/ has at least one *.md entry"
else
  bad "graph/memory/ has at least one *.md entry"
fi

# --- group 2: the first entry's frontmatter carries the required keys --------
if [[ "${#MEMORY_ENTRIES[@]}" -gt 0 ]]; then
  ENTRY="${MEMORY_ENTRIES[0]}"
  FRONTMATTER_CHECK="$(python3 - "$ENTRY" <<'PY'
import re
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as fh:
    lines = fh.readlines()

if not lines or lines[0].strip() != "---":
    print("NO_FRONTMATTER")
    raise SystemExit(0)

body = []
closed = False
for line in lines[1:]:
    if line.strip() == "---":
        closed = True
        break
    body.append(line)

if not closed:
    print("UNCLOSED_FRONTMATTER")
    raise SystemExit(0)

keys = {}
for line in body:
    m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", line)
    if m:
        keys[m.group(1)] = m.group(2).strip()

required = ["type", "date", "contributor", "outcome", "source_nodes"]
missing = [k for k in required if k not in keys]
if missing:
    print("MISSING_KEYS:" + ",".join(missing))
    raise SystemExit(0)

outcome = keys["outcome"].strip("'\"")
if outcome not in {"useful", "dead_end", "corrected"}:
    print("BAD_OUTCOME:" + outcome)
    raise SystemExit(0)

print("OK")
PY
)"
  if [[ "$FRONTMATTER_CHECK" == "OK" ]]; then
    ok "first memory entry frontmatter has type/date/contributor/outcome/source_nodes with a valid outcome"
  else
    bad "first memory entry frontmatter is well-formed (got '$FRONTMATTER_CHECK' for $ENTRY)"
  fi
else
  bad "first memory entry frontmatter has type/date/contributor/outcome/source_nodes with a valid outcome (no entry found)"
fi

# --- group 3: LESSONS.md exists, non-empty, carries the reflect marker -------
if [[ -s "$LESSONS" ]]; then
  ok "graph/reflections/LESSONS.md exists and is non-empty"
else
  bad "graph/reflections/LESSONS.md exists and is non-empty"
fi
if [[ -f "$LESSONS" ]]; then
  check_contains "LESSONS.md carries the graphify reflect auto-generated marker" "$LESSONS" "$REFLECT_MARKER"
else
  bad "LESSONS.md carries the graphify reflect auto-generated marker (file missing)"
fi

# --- group 4: graph/memory/ is committed, not git-ignored --------------------
if git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if git -C "$ROOT" check-ignore -q graph/memory; then
    bad "graph/memory is not git-ignored"
  else
    ok "graph/memory is not git-ignored"
  fi
else
  ok "graph/memory git-ignore check skipped (not a git repo)"
fi

# --- group 5: weekly-playbook.yml wires the reflect step ---------------------
check_contains "weekly-playbook.yml invokes graphify reflect" "$WORKFLOW" "graphify reflect"
check_contains "weekly-playbook.yml passes --memory-dir graph/memory" "$WORKFLOW" "--memory-dir graph/memory"
check_contains "weekly-playbook.yml writes graph/reflections/LESSONS.md" "$WORKFLOW" "graph/reflections/LESSONS.md"

# --- group 6: harness instructions tell agents to save memory entries --------
INSTRUCTION_FILES=(
  "scripts/ralph/PROMPT.md"
  ".claude/agents/chief-architect.md"
  ".claude/agents/code-review-orchestrator.md"
  ".claude/agents/shared/adepthood-constraints.md"
  ".claude/skills/graph/SKILL.md"
)
for rel in "${INSTRUCTION_FILES[@]}"; do
  f="$ROOT/$rel"
  check_contains "$rel mentions save-result" "$f" "save-result"
  check_contains "$rel mentions graph/memory" "$f" "graph/memory"
done

# --- group 7 (optional, offline-safe): live save-result -> reflect round-trip -
# Build the fixture entries with the real save-result subcommand so the test
# exercises the exact on-disk format reflect consumes, then confirm reflect
# surfaces a node corroborated by two useful results. The reflect call runs in
# a subshell cd'd into the fixture dir so it never auto-reads a real
# graphify-out/graph.json from the repo root (which would drop the synthetic
# node as stale). Skipped when the CLI is absent, so the test stays offline.
if command -v graphify >/dev/null 2>&1; then
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  RC=0
  graphify save-result --question "fixture query one" \
    --answer "cites FixtureNodeXYZ" --type query --nodes FixtureNodeXYZ \
    --outcome useful --memory-dir "$TMP" >"$TMP/save.log" 2>&1 || RC=$?
  graphify save-result --question "fixture query two" \
    --answer "cites FixtureNodeXYZ again" --type query --nodes FixtureNodeXYZ \
    --outcome useful --memory-dir "$TMP" >>"$TMP/save.log" 2>&1 || RC=$?
  ( cd "$TMP" && graphify reflect --memory-dir "$TMP" --out "$TMP/LESSONS.md" ) \
    >"$TMP/reflect.log" 2>&1 || RC=$?
  if [[ "$RC" -eq 0 && -f "$TMP/LESSONS.md" ]] \
     && grep -qF -- "FixtureNodeXYZ" "$TMP/LESSONS.md"; then
    ok "live save-result then reflect surfaces a corroborated fixture node"
  else
    bad "live save-result then reflect surfaces a corroborated fixture node (rc=$RC)"
  fi
else
  ok "live save-result/reflect check skipped (graphify not on PATH)"
fi

# --- summary ------------------------------------------------------------------
echo
echo "memory-loop tests: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]]
