"""Gate the served Course for completeness and generate its two inventories.

Issue #3070. ``sync_content --check`` proves ``backend/content/`` is the pinned
upstream commit byte-for-byte, and ``build_stage_correspondence --check`` proves
the stage correspondence is generated from it. Neither proves the Course a
reader is served is *complete*: a heading-only chapter or a skipped chapter
number passes both. This script closes that gap:

    python -m scripts.content_completeness           # regenerate the inventories, then gate
    python -m scripts.content_completeness --check   # CI: gate and diff, write nothing

The served Course is exactly the manifest's chapters, stage intros and site
resources; vendored files the manifest does not name (``backup/``, the export
tables of contents) are out of scope. Every stage intro shares its file with
chapter 1 upstream, so each file is graded once and carries every ref that
serves it.

Checks (each in :data:`CHECKS`, each proven to fire by a violating fixture in
``tests/scripts/test_content_completeness.py``):

* ``stage_coverage`` -- each stage 1..``STAGE_COUNT`` has exactly one intro and
  at least one chapter, and nothing lies outside that range.
* ``duplicate_ref`` -- chapter ids, per-stage chapter slugs, intro ids and
  resource slugs are unique.
* ``thin_chapter`` -- a chapter body has at least ``MIN_CHAPTER_WORDS`` words.
* ``numbering_gap`` -- per stage, chapter numbers run 1..n with no gap and no
  repeat.
* ``broken_relative_link`` -- a relative link or image resolves to a file
  inside the content dir, and a ``.md#fragment`` names a heading there.
* ``broken_anchor`` -- an in-file ``#anchor`` names a heading of that file.
* ``insecure_external_link`` / ``redirect_wrapper_link`` -- external links are
  https and are not Google Docs ``google.com/url`` redirect wrappers.

Only ``thin_chapter`` and ``numbering_gap`` are content the owner must write
upstream, so only they may be recorded in ``src/curriculum/content_gaps.json``
(each pending owner review). A recorded gap that no longer reproduces fails as
stale, so fixing the content upstream forces the record to shrink. Link
failures are never waivable.

Inventories (regenerated by default mode, byte-compared by ``--check``):

* ``src/curriculum/source_references.json`` -- every external link in served
  content, by file and the refs serving it. A draft input to the owner's
  bibliography, explicitly **not** a bibliography and carrying no rights status.
* ``src/curriculum/practice_recommendations.json`` -- every chapter whose title
  names a practice or protocol, each ``unreviewed``. Mapping decisions belong in
  a separate owner-reviewed sidecar, since regeneration overwrites this file.

Like its siblings this script imports nothing from ``src/``: the CI job
installs only ``httpx`` and ``jsonschema``. ``tests/test_content_completeness_parity.py``
pins its frontmatter stripper and stage count to the server's.

Exit codes: 0 when the Course is complete (or every gap is recorded) and the
inventories are current; 1 otherwise, with every problem on stderr.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Final
from urllib.parse import urlsplit

# Stages in the program, from the stage-correspondence generator's stage ids
# (this script cannot import ``src/`` in the CI drift job); the parity test pins
# it to ``domain.constants.TOTAL_STAGES``.
from scripts.build_stage_correspondence import STAGE_COUNT
from scripts.sync_content import CONTENT_REPO, SyncContentError, read_content_version

_BACKEND_DIR = Path(__file__).resolve().parents[1]

#: The vendored content tree (mirrors ``sync_content``'s default target).
CONTENT_DIR = _BACKEND_DIR / "content"

_CURRICULUM_DIR = _BACKEND_DIR / "src" / "curriculum"

#: Hand-reviewed record of known content gaps (never written by this script).
GAPS_PATH = _CURRICULUM_DIR / "content_gaps.json"
#: Generated inventories.
SOURCES_PATH = _CURRICULUM_DIR / "source_references.json"
PRACTICES_PATH = _CURRICULUM_DIR / "practice_recommendations.json"

#: Minimum body words for a chapter, counted after the frontmatter with heading
#: lines excluded. On the pinned tree teal-7 has 0, orange-7 has 29 and the
#: next-thinnest (orange-13) has 75, so the floor separates a missing body from
#: a short one with room on both sides.
MIN_CHAPTER_WORDS: Final[int] = 50

#: The only kinds a gaps record may waive: content the owner writes upstream.
WAIVABLE_KINDS: Final[frozenset[str]] = frozenset({"thin_chapter", "numbering_gap"})

#: Google Docs exports wrap every link as ``https://www.google.com/url?q=...``.
REDIRECT_WRAPPER_HOSTS: Final[frozenset[str]] = frozenset({"google.com", "www.google.com"})
_REDIRECT_WRAPPER_PATH = "/url"

#: A chapter title naming a practice recommendation ("The Practice of Blue",
#: "Alternatives for Teal Practice", "The Grounding Protocol: 5-4-3-2-1").
PRACTICE_TITLE: Final[re.Pattern[str]] = re.compile(r"\b(?:practices?|protocol)\b", re.IGNORECASE)

#: The status every generated practice entry carries.
UNREVIEWED: Final[str] = "unreviewed"

NOT_A_BIBLIOGRAPHY: Final[str] = (
    "Generated by `python -m scripts.content_completeness` from the served Course "
    "(issue #3070). This is an inventory of the external links in served content, "
    "NOT a bibliography: it carries no author, edition or rights/permissions status, "
    "and a link is not a citation. The owner's bibliography is built from it."
)

PRACTICES_NOTICE: Final[str] = (
    "Generated by `python -m scripts.content_completeness` from the manifest "
    "(issue #3070): every chapter whose title names a practice or protocol. Every "
    "status is 'unreviewed'; regeneration overwrites this file, so owner-reviewed "
    "mappings to practice presets belong in a separate sidecar keyed by id."
)

_GAP_OWNER_REVIEW = "pending"
_GAP_DOCUMENT_KEYS = frozenset({"description", "gaps"})

_FRONTMATTER_FENCE = "---"
_BOM = "\ufeff"

_HEADING = re.compile(r"^\s{0,3}#{1,6}\s+(?P<text>.*?)(?:\s+#+)?\s*$")
_INLINE_LINK = re.compile(
    r"!?\[(?P<text>[^\]]*)\]\(\s*(?:<(?P<angled>[^>]*)>|(?P<bare>[^)\s]+))(?:\s+\"[^\"]*\")?\s*\)"
)
_AUTOLINK = re.compile(r"<(?P<url>[a-zA-Z][a-zA-Z0-9+.-]*://[^>\s]+)>")
_SLUG_DROP = re.compile(r"[^\w\- ]")
_EXTERNAL_SCHEMES = frozenset({"http", "https"})


class ContentCompletenessError(Exception):
    """The inputs cannot be graded: unreadable manifest, escaping path, bad gaps record."""


@dataclass(frozen=True, order=True)
class Finding:
    """One completeness failure, identified by ``(kind, key)``."""

    kind: str
    key: str
    detail: str


@dataclass(frozen=True)
class Gap:
    """One recorded, owner-pending content gap the gate tolerates while it reproduces."""

    kind: str
    key: str
    reason: str
    owner_review: str
    upstream: str
    issue: str


_GAP_KEYS = frozenset(Gap.__dataclass_fields__)


@dataclass(frozen=True)
class Chapter:
    """The manifest fields of one chapter the gate needs."""

    id: str
    stage: int
    chapter: int
    slug: str
    title: str
    path: str


@dataclass(frozen=True)
class Document:
    """One served file, graded once, with every ref that serves it."""

    path: str
    refs: tuple[str, ...]
    body: str


@dataclass(frozen=True)
class Link:
    """A markdown link or image target and its text."""

    text: str
    target: str


@dataclass(frozen=True)
class Corpus:
    """The served Course: its manifest entries and de-duplicated documents."""

    content_dir: Path
    chapters: tuple[Chapter, ...]
    intros: tuple[dict[str, Any], ...]
    resources: tuple[dict[str, Any], ...]
    documents: tuple[Document, ...]

    def body(self, path: str) -> str:
        """Return the served body of the document at manifest ``path``."""
        return next(document.body for document in self.documents if document.path == path)


# --- reading -------------------------------------------------------------------------


def strip_frontmatter(text: str) -> str:
    """Drop a leading ``---`` YAML block exactly as the content repository does.

    Only a fence on line 1 (after an optional BOM) counts, and an unclosed block
    returns ``text`` unchanged. Pinned to ``services.content_repository`` by
    ``tests/test_content_completeness_parity.py``.
    """
    lines = text.removeprefix(_BOM).splitlines(keepends=True)
    if not lines or lines[0].rstrip() != _FRONTMATTER_FENCE:
        return text
    for index in range(1, len(lines)):
        if lines[index].rstrip() == _FRONTMATTER_FENCE:
            return "".join(lines[index + 1 :])
    return text


def _resolve_inside(content_dir: Path, relative: str) -> Path:
    """Resolve a manifest path, refusing any that leaves ``content_dir``."""
    path = (content_dir / relative).resolve()
    if not path.is_relative_to(content_dir.resolve()):
        msg = f"manifest path {relative!r} resolves outside the content dir"
        raise ContentCompletenessError(msg)
    return path


def _read_served(content_dir: Path, relative: str) -> str:
    """Return the served body (frontmatter stripped) of one manifest path."""
    try:
        text = _resolve_inside(content_dir, relative).read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        msg = f"manifest path {relative!r} is missing from {content_dir}"
        raise ContentCompletenessError(msg) from exc
    return strip_frontmatter(text)


def _load_manifest(content_dir: Path) -> dict[str, Any]:
    """Read ``manifest.json`` or raise a readable error."""
    path = content_dir / "manifest.json"
    try:
        manifest: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        msg = f"cannot read manifest {path}: {exc}"
        raise ContentCompletenessError(msg) from exc
    return manifest


def _served_refs(
    chapters: tuple[Chapter, ...],
    intros: tuple[dict[str, Any], ...],
    resources: tuple[dict[str, Any], ...],
) -> dict[str, list[str]]:
    """Map each served path to its refs, in manifest order (chapters, intros, resources)."""
    refs: dict[str, list[str]] = {}
    pairs = [
        *((chapter.path, chapter.id) for chapter in chapters),
        *((intro["path"], intro["id"]) for intro in intros),
        *((resource["path"], f"resource:{resource['slug']}") for resource in resources),
    ]
    for path, ref in pairs:
        refs.setdefault(path, []).append(ref)
    return refs


def load_corpus(content_dir: Path) -> Corpus:
    """Load the served Course under ``content_dir``."""
    manifest = _load_manifest(content_dir)
    chapters = tuple(
        Chapter(
            id=entry["id"],
            stage=entry["stage"],
            chapter=entry["chapter"],
            slug=entry["slug"],
            title=entry["title"],
            path=entry["path"],
        )
        for entry in manifest["chapters"]
    )
    intros = tuple(manifest["stage_intros"])
    resources = tuple(manifest["site_resources"])
    documents = tuple(
        Document(path=path, refs=tuple(refs), body=_read_served(content_dir, path))
        for path, refs in _served_refs(chapters, intros, resources).items()
    )
    return Corpus(content_dir, chapters, intros, resources, documents)


# --- text helpers ----------------------------------------------------------------------


def _is_heading(line: str) -> bool:
    return _HEADING.match(line) is not None


def body_word_count(text: str) -> int:
    """Count words in the served body, excluding the frontmatter and heading lines."""
    lines = strip_frontmatter(text).splitlines()
    return sum(len(line.split()) for line in lines if not _is_heading(line))


def heading_slug(text: str) -> str:
    """GitHub-style anchor slug: lowercase, punctuation dropped, spaces to hyphens."""
    return _SLUG_DROP.sub("", text.strip().lower()).replace(" ", "-")


def heading_slugs(body: str) -> set[str]:
    """Every anchor a body's headings define, with ``-1``/``-2`` for repeats."""
    seen: Counter[str] = Counter()
    slugs: set[str] = set()
    for line in body.splitlines():
        match = _HEADING.match(line)
        if match is None:
            continue
        slug = heading_slug(match.group("text"))
        slugs.add(f"{slug}-{seen[slug]}" if seen[slug] else slug)
        seen[slug] += 1
    return slugs


def iter_links(body: str) -> Iterator[Link]:
    """Yield inline links, images and ``<scheme://...>`` autolinks in ``body``."""
    for match in _INLINE_LINK.finditer(body):
        yield Link(match.group("text"), match.group("angled") or match.group("bare"))
    for match in _AUTOLINK.finditer(body):
        yield Link("", match.group("url"))


def _is_external(target: str) -> bool:
    return urlsplit(target).scheme.lower() in _EXTERNAL_SCHEMES


def _is_relative(target: str) -> bool:
    return not urlsplit(target).scheme and not target.startswith("#")


# --- checks ------------------------------------------------------------------------------


def _coverage_problem(stage: int, intro_count: int, chapter_count: int) -> str | None:
    """Return what is wrong with one stage's coverage, if anything."""
    if not 1 <= stage <= STAGE_COUNT:
        return f"stage {stage} is outside 1..{STAGE_COUNT}"
    if intro_count != 1:
        return f"{intro_count} stage intros (need exactly 1)"
    if chapter_count == 0:
        return "no chapters"
    return None


def check_stage_coverage(corpus: Corpus) -> list[Finding]:
    """Each stage has exactly one intro and a chapter; no stage is out of range."""
    intros = Counter(intro["stage"] for intro in corpus.intros)
    chapters = Counter(chapter.stage for chapter in corpus.chapters)
    stages = sorted(set(range(1, STAGE_COUNT + 1)) | set(intros) | set(chapters))
    findings = []
    for stage in stages:
        problem = _coverage_problem(stage, intros[stage], chapters[stage])
        if problem is not None:
            findings.append(Finding("stage_coverage", str(stage), problem))
    return findings


def _duplicates(label: str, keys: list[str]) -> list[Finding]:
    """One finding per key that occurs more than once."""
    return [
        Finding("duplicate_ref", f"{label}:{key}", f"used {count} times")
        for key, count in sorted(Counter(keys).items())
        if count > 1
    ]


def check_duplicate_ref(corpus: Corpus) -> list[Finding]:
    """Chapter ids, per-stage chapter slugs, intro ids and resource slugs are unique."""
    return [
        *_duplicates("chapter-id", [chapter.id for chapter in corpus.chapters]),
        *_duplicates("chapter-slug", [f"{c.stage}/{c.slug}" for c in corpus.chapters]),
        *_duplicates("intro-id", [intro["id"] for intro in corpus.intros]),
        *_duplicates("resource-slug", [resource["slug"] for resource in corpus.resources]),
    ]


def check_thin_chapter(corpus: Corpus) -> list[Finding]:
    """Every chapter body reaches ``MIN_CHAPTER_WORDS``."""
    findings = []
    for chapter in corpus.chapters:
        words = body_word_count(corpus.body(chapter.path))
        if words < MIN_CHAPTER_WORDS:
            detail = f"{words} body words, under {MIN_CHAPTER_WORDS}"
            findings.append(Finding("thin_chapter", chapter.id, detail))
    return findings


def _stage_numbering(stage: int, numbers: list[int]) -> list[Finding]:
    """Missing and repeated chapter numbers in one stage."""
    counts = Counter(numbers)
    missing = [
        Finding("numbering_gap", f"{stage}:{number}", f"chapter {number} is missing")
        for number in range(1, max(counts) + 1)
        if number not in counts
    ]
    repeated = [
        Finding(
            "numbering_gap", f"{stage}:{number}:duplicate", f"chapter {number} appears {n} times"
        )
        for number, n in sorted(counts.items())
        if n > 1
    ]
    return missing + repeated


def check_numbering_gap(corpus: Corpus) -> list[Finding]:
    """Per stage, chapter numbers run 1..n with no gap and no repeat."""
    by_stage: dict[int, list[int]] = {}
    for chapter in corpus.chapters:
        by_stage.setdefault(chapter.stage, []).append(chapter.chapter)
    return [
        finding
        for stage, numbers in sorted(by_stage.items())
        for finding in _stage_numbering(stage, numbers)
    ]


def _documents_links(corpus: Corpus) -> Iterator[tuple[Document, Link]]:
    """Every link in every served document, each file once."""
    for document in corpus.documents:
        for link in iter_links(document.body):
            yield document, link


def _link_finding(kind: str, document: Document, target: str, detail: str) -> Finding:
    return Finding(kind, f"{document.path} -> {target}", detail)


def _relative_problem(corpus: Corpus, document: Document, target: str) -> str | None:
    """Return why a relative link does not resolve inside the content dir, if it does not."""
    path_part, _, fragment = target.partition("#")
    source = PurePosixPath(document.path).parent / path_part
    resolved = (corpus.content_dir / source).resolve()
    if not resolved.is_relative_to(corpus.content_dir.resolve()):
        return "resolves outside the content dir"
    if not resolved.is_file():
        return "target file does not exist"
    return _fragment_problem(resolved, fragment)


def _fragment_problem(target: Path, fragment: str) -> str | None:
    """Return why ``#fragment`` names no heading of a markdown ``target``, if it does not."""
    if not fragment or target.suffix != ".md":
        return None
    body = strip_frontmatter(target.read_text(encoding="utf-8"))
    return None if fragment in heading_slugs(body) else f"no heading #{fragment} in the target"


def check_broken_relative_link(corpus: Corpus) -> list[Finding]:
    """Relative links and images resolve inside the content dir."""
    findings = []
    for document, link in _documents_links(corpus):
        if not _is_relative(link.target):
            continue
        problem = _relative_problem(corpus, document, link.target)
        if problem is not None:
            findings.append(_link_finding("broken_relative_link", document, link.target, problem))
    return findings


def check_broken_anchor(corpus: Corpus) -> list[Finding]:
    """In-file ``#anchor`` links name a heading of the same file."""
    return [
        _link_finding("broken_anchor", document, link.target, "no such heading in this file")
        for document, link in _documents_links(corpus)
        if link.target.startswith("#") and link.target[1:] not in heading_slugs(document.body)
    ]


def check_insecure_external_link(corpus: Corpus) -> list[Finding]:
    """External links use https."""
    return [
        _link_finding("insecure_external_link", document, link.target, "plain http")
        for document, link in _documents_links(corpus)
        if urlsplit(link.target).scheme.lower() == "http"
    ]


def _is_redirect_wrapper(target: str) -> bool:
    parts = urlsplit(target)
    host = (parts.hostname or "").lower()
    return host in REDIRECT_WRAPPER_HOSTS and parts.path == _REDIRECT_WRAPPER_PATH


def check_redirect_wrapper_link(corpus: Corpus) -> list[Finding]:
    """No link is a Google Docs ``google.com/url`` redirect wrapper."""
    return [
        _link_finding("redirect_wrapper_link", document, link.target, "google.com/url wrapper")
        for document, link in _documents_links(corpus)
        if _is_redirect_wrapper(link.target)
    ]


#: Every check the gate runs, keyed by the finding kind it reports.
CHECKS: Final[dict[str, Callable[[Corpus], list[Finding]]]] = {
    "stage_coverage": check_stage_coverage,
    "duplicate_ref": check_duplicate_ref,
    "thin_chapter": check_thin_chapter,
    "numbering_gap": check_numbering_gap,
    "broken_relative_link": check_broken_relative_link,
    "broken_anchor": check_broken_anchor,
    "insecure_external_link": check_insecure_external_link,
    "redirect_wrapper_link": check_redirect_wrapper_link,
}


def audit(corpus: Corpus) -> list[Finding]:
    """Run every check and return all findings, sorted."""
    return sorted(finding for check in CHECKS.values() for finding in check(corpus))


# --- the gaps record and the gate --------------------------------------------------------


def _blank_fields(entry: dict[str, Any]) -> list[str]:
    """The known fields of ``entry`` whose value is empty or whitespace."""
    return sorted(key for key in _GAP_KEYS & set(entry) if not str(entry[key]).strip())


def _shape_problem(entry: dict[str, Any]) -> str | None:
    """Return why an entry's keys are wrong (unknown, missing or blank), if they are."""
    problems = {
        "unknown keys": sorted(set(entry) - _GAP_KEYS),
        "missing keys": sorted(_GAP_KEYS - set(entry)),
        "blank fields": _blank_fields(entry),
    }
    found = [f"{label}: {', '.join(keys)}" for label, keys in problems.items() if keys]
    return found[0] if found else None


def _gap_problem(entry: dict[str, Any]) -> str | None:
    """Return why one gaps-record entry is invalid, if it is."""
    shape = _shape_problem(entry)
    if shape is not None:
        return shape
    if entry["kind"] not in WAIVABLE_KINDS:
        return f"kind {entry['kind']!r} is not waivable; fix it instead"
    if entry["owner_review"] != _GAP_OWNER_REVIEW:
        return f"owner_review must be {_GAP_OWNER_REVIEW!r}; delete the gap once it is fixed"
    return None


def _read_json(path: Path) -> object:
    """Parse the JSON at ``path`` or raise a readable error."""
    try:
        document: object = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        msg = f"{path} not found"
        raise ContentCompletenessError(msg) from exc
    except ValueError as exc:
        msg = f"{path} is not JSON: {exc}"
        raise ContentCompletenessError(msg) from exc
    return document


def _gap_entries(path: Path) -> list[Any]:
    """Read the record's ``gaps`` list, validating the document's own shape."""
    document = _read_json(path)
    if not isinstance(document, dict) or not set(document) <= _GAP_DOCUMENT_KEYS:
        msg = f"{path} must be an object with only {sorted(_GAP_DOCUMENT_KEYS)}"
        raise ContentCompletenessError(msg)
    entries = document.get("gaps")
    if not isinstance(entries, list):
        msg = f"{path} needs a 'gaps' list"
        raise ContentCompletenessError(msg)
    return entries


def _entry_problem(entry: object) -> str | None:
    """Return why one raw entry cannot become a :class:`Gap`, if it cannot."""
    if not isinstance(entry, dict):
        return "is not an object"
    return _gap_problem(entry)


def load_gaps(path: Path) -> list[Gap]:
    """Load and validate the hand-reviewed gaps record."""
    gaps: dict[tuple[str, str], Gap] = {}
    for index, entry in enumerate(_gap_entries(path)):
        problem = _entry_problem(entry)
        if problem is not None:
            msg = f"{path} gap {index}: {problem}"
            raise ContentCompletenessError(msg)
        gap = Gap(**entry)
        if (gap.kind, gap.key) in gaps:
            msg = f"{path} gap {index}: duplicate record for {gap.kind} {gap.key}"
            raise ContentCompletenessError(msg)
        gaps[gap.kind, gap.key] = gap
    return list(gaps.values())


def _identity(item: Finding | Gap) -> tuple[str, str]:
    return item.kind, item.key


def gate(findings: list[Finding], gaps: list[Gap]) -> tuple[list[Finding], list[Gap]]:
    """Return ``(unrecorded findings, stale gaps)``; the gate passes when both are empty."""
    recorded = set(map(_identity, gaps))
    found = set(map(_identity, findings))
    unrecorded = [finding for finding in findings if _identity(finding) not in recorded]
    return unrecorded, [gap for gap in gaps if _identity(gap) not in found]


# --- inventories ---------------------------------------------------------------------------


def _external_links(body: str) -> list[dict[str, str]]:
    """The distinct external links in ``body``, sorted by URL then text."""
    pairs = {(link.target, link.text.strip()) for link in iter_links(body)}
    return [{"text": text, "url": url} for url, text in sorted(pairs) if _is_external(url)]


def build_source_references(corpus: Corpus) -> dict[str, Any]:
    """Inventory every external link in served content, by file and serving refs."""
    try:
        sha = read_content_version(corpus.content_dir)["sha"]
    except SyncContentError as exc:
        raise ContentCompletenessError(str(exc)) from exc
    entries = [
        {"path": document.path, "refs": list(document.refs), "links": links}
        for document in corpus.documents
        if (links := _external_links(document.body))
    ]
    return {
        "notice": NOT_A_BIBLIOGRAPHY,
        "source": {"repo": CONTENT_REPO, "sha": sha},
        "entries": entries,
    }


def build_practice_recommendations(corpus: Corpus) -> dict[str, Any]:
    """List every chapter whose title names a practice or protocol, unreviewed."""
    entries = [
        {
            "id": chapter.id,
            "stage": chapter.stage,
            "chapter": chapter.chapter,
            "title": chapter.title,
            "status": UNREVIEWED,
        }
        for chapter in corpus.chapters
        if PRACTICE_TITLE.search(chapter.title)
    ]
    return {"notice": PRACTICES_NOTICE, "entries": entries}


def render(inventory: dict[str, Any]) -> str:
    """Serialise deterministically: sorted keys, two-space indent, no timestamp."""
    return json.dumps(inventory, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


# --- CLI ---------------------------------------------------------------------------------------


def _drift(rendered: str, path: Path) -> str | None:
    """Return why a committed inventory differs from ``rendered``, if it does."""
    try:
        committed = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return f"{path} is missing — run `python -m scripts.content_completeness`"
    if committed != rendered:
        return f"{path} is stale — run `python -m scripts.content_completeness`"
    return None


def _gate_report(corpus: Corpus, gaps_path: Path) -> list[str]:
    """Every unrecorded finding and stale gap, as stderr lines."""
    unrecorded, stale = gate(audit(corpus), load_gaps(gaps_path))
    return [
        *(f"unrecorded finding: {f.kind} {f.key} ({f.detail})" for f in unrecorded),
        *(f"stale gap: {g.kind} {g.key} no longer reproduces; remove it" for g in stale),
    ]


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse the CLI flags; every path defaults to the committed location."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on gaps or drift; write nothing")
    parser.add_argument("--content-dir", type=Path, default=CONTENT_DIR)
    parser.add_argument("--gaps", type=Path, default=GAPS_PATH)
    parser.add_argument("--sources", type=Path, default=SOURCES_PATH)
    parser.add_argument("--practices", type=Path, default=PRACTICES_PATH)
    return parser.parse_args(argv)


def _run(args: argparse.Namespace) -> list[str]:
    """Gate the Course and check or write the inventories; return every problem."""
    corpus = load_corpus(args.content_dir)
    problems = _gate_report(corpus, args.gaps)
    inventories = {
        args.sources: render(build_source_references(corpus)),
        args.practices: render(build_practice_recommendations(corpus)),
    }
    for path, rendered in inventories.items():
        if args.check:
            problems.extend(filter(None, [_drift(rendered, path)]))
        else:
            path.write_text(rendered, encoding="utf-8")
    return problems


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Returns 0 when complete and current, 1 on any problem."""
    args = _parse_args(argv)
    try:
        problems = _run(args)
    except ContentCompletenessError as exc:
        problems = [str(exc)]
    for problem in problems:
        sys.stderr.write(f"{problem}\n")
    if problems:
        return 1
    sys.stdout.write("Course content is complete and its inventories are current\n")
    return 0


if __name__ == "__main__":  # pragma: no cover — exercised by the subprocess meta-test
    sys.exit(main())
