import type { Habit } from './Habits.types';

export const HABIT_DEFAULTS: Habit[] = [
  {
    id: 1,
    stage: 'Clear Light',
    name: 'High Flow Activity',
    icon: '🎨',
    streak: 0,
    energy_cost: 7,
    energy_return: 9,
    start_date: new Date(2025, 3, 1),
    goals: [
      {
        id: 1,
        tier: 'low',
        title: 'Minimal Flow',
        target: 3,
        target_unit: 'hours',
        frequency: 1,
        frequency_unit: 'per_week',
        is_additive: true,
      },
      {
        id: 2,
        tier: 'clear',
        title: 'Consistent Flow',
        target: 3,
        target_unit: 'hours',
        frequency: 2,
        frequency_unit: 'per_week',
        is_additive: true,
      },
      {
        id: 3,
        tier: 'stretch',
        title: 'Peak Flow',
        target: 3,
        target_unit: 'hours',
        frequency: 3,
        frequency_unit: 'per_week',
        is_additive: true,
      },
    ],
  },
  {
    id: 2,
    stage: 'Ultraviolet',
    name: 'Food Choices',
    icon: '🥗',
    streak: 0,
    energy_cost: 6,
    energy_return: 8,
    start_date: new Date(2025, 3, 5),
    goals: [
      {
        id: 4,
        tier: 'low',
        title: 'Calorie Break-Even',
        target: 2500,
        target_unit: 'kcal',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
      {
        id: 5,
        tier: 'clear',
        title: 'Calorie Deficit',
        target: 1900,
        target_unit: 'kcal',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
      {
        id: 6,
        tier: 'stretch',
        title: 'Higher Calorie Deficit',
        target: 1600,
        target_unit: 'kcal',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
    ],
  },
  {
    id: 3,
    stage: 'Turquoise',
    name: 'Limit Caffeine',
    icon: '☕',
    streak: 0,
    energy_cost: 4,
    energy_return: 5,
    start_date: new Date(2025, 3, 10),
    goals: [
      {
        id: 7,
        tier: 'low',
        title: 'Mindful Consumption',
        target: 300,
        target_unit: 'mg',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
      {
        id: 8,
        tier: 'clear',
        title: 'Moderate Intake',
        target: 200,
        target_unit: 'mg',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
      {
        id: 9,
        tier: 'stretch',
        title: 'Abstinence',
        target: 0,
        target_unit: 'mg',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
    ],
  },
  {
    id: 4,
    stage: 'Yellow',
    name: 'Blissy Meditation',
    icon: '🧘',
    streak: 0,
    energy_cost: 5,
    energy_return: 8,
    start_date: new Date(2025, 2, 25),
    goals: [
      {
        id: 10,
        tier: 'low',
        title: 'Minimal Sit',
        target: 30,
        target_unit: 'minutes',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: true,
      },
      {
        id: 11,
        tier: 'clear',
        title: 'Full Sit',
        target: 45,
        target_unit: 'minutes',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: true,
      },
      {
        id: 12,
        tier: 'stretch',
        title: 'Mini-Retreat',
        target: 120,
        target_unit: 'minutes',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: true,
      },
    ],
  },
  {
    id: 5,
    stage: 'Green',
    name: 'Sangha',
    icon: '🧘‍♀️',
    streak: 1,
    energy_cost: 8,
    energy_return: 9,
    start_date: new Date(2025, 3, 15),
    goals: [
      {
        id: 13,
        tier: 'low',
        title: 'Community Contact',
        target: 1,
        target_unit: 'sessions',
        frequency: 1,
        frequency_unit: 'per_week',
        is_additive: true,
      },
      {
        id: 14,
        tier: 'clear',
        title: 'Regular Participation',
        target: 2,
        target_unit: 'sessions',
        frequency: 1,
        frequency_unit: 'per_week',
        is_additive: true,
      },
      {
        id: 15,
        tier: 'stretch',
        title: 'Deep Engagement',
        target: 3,
        target_unit: 'sessions',
        frequency: 1,
        frequency_unit: 'per_week',
        is_additive: true,
      },
    ],
  },
  {
    id: 6,
    stage: 'Orange',
    name: 'Exercise',
    icon: '🏃‍♂️',
    streak: 4,
    energy_cost: 7,
    energy_return: 8,
    start_date: new Date(2025, 2, 20),
    goals: [
      {
        id: 16,
        tier: 'low',
        title: 'Keeping Moving',
        target: 20,
        target_unit: 'minutes',
        frequency: 3,
        frequency_unit: 'per_week',
        is_additive: true,
      },
      {
        id: 17,
        tier: 'clear',
        title: 'Regular Training',
        target: 30,
        target_unit: 'minutes',
        frequency: 4,
        frequency_unit: 'per_week',
        is_additive: true,
      },
      {
        id: 18,
        tier: 'stretch',
        title: 'Disciplined Regimen',
        target: 60,
        target_unit: 'minutes',
        frequency: 5,
        frequency_unit: 'per_week',
        is_additive: true,
      },
    ],
  },
  {
    id: 7,
    stage: 'Blue',
    name: 'Scrolling',
    icon: '📱',
    streak: 0,
    energy_cost: 3,
    energy_return: 6,
    start_date: new Date(2025, 3, 8),
    goals: [
      {
        id: 19,
        tier: 'low',
        title: 'Mindful Usage',
        target: 60,
        target_unit: 'minutes',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
      {
        id: 20,
        tier: 'clear',
        title: 'Digital Minimalism',
        target: 30,
        target_unit: 'minutes',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
      {
        id: 21,
        tier: 'stretch',
        title: 'Cellular Sobriety',
        target: 0,
        target_unit: 'minutes',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
    ],
  },
  {
    id: 8,
    stage: 'Red',
    name: 'Alcohol/Intoxicants',
    icon: '🍷',
    streak: 6,
    energy_cost: 5,
    energy_return: 7,
    start_date: new Date(2025, 2, 28),
    goals: [
      {
        id: 22,
        tier: 'low',
        title: 'Moderation',
        target: 3,
        target_unit: 'drinks',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
      {
        id: 23,
        tier: 'clear',
        title: 'Occasional Only',
        target: 2,
        target_unit: 'drinks',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
      {
        id: 24,
        tier: 'stretch',
        title: 'Full Abstenance',
        target: 0,
        target_unit: 'drinks',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: false,
      },
    ],
  },
  {
    id: 9,
    stage: 'Purple',
    name: 'Water (and Vitamins!)',
    icon: '💧',
    streak: 7,
    energy_cost: 4,
    energy_return: 7,
    start_date: new Date(2025, 2, 15),
    goals: [
      {
        id: 25,
        tier: 'low',
        title: 'Basic Hydration',
        target: 32,
        target_unit: 'oz',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: true,
      },
      {
        id: 26,
        tier: 'clear',
        title: 'Optimal Hydration',
        target: 64,
        target_unit: 'oz',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: true,
      },
      {
        id: 27,
        tier: 'stretch',
        title: 'Complete Protocol',
        target: 128,
        target_unit: 'oz',
        frequency: 1,
        frequency_unit: 'per_day',
        is_additive: true,
      },
    ],
  },
  {
    id: 10,
    stage: 'Beige',
    name: 'Take work seriously',
    icon: '💼',
    streak: 10,
    energy_cost: 5,
    energy_return: 8,
    start_date: new Date(2025, 2, 5),
    goals: [
      {
        id: 28,
        tier: 'low',
        title: 'Employment',
        target: 1,
        target_unit: 'job',
        frequency: 5,
        frequency_unit: 'per_week',
        is_additive: true,
      },
      {
        id: 29,
        tier: 'clear',
        title: 'Fulfilment',
        target: 1,
        target_unit: 'job',
        frequency: 5,
        frequency_unit: 'per_week',
        is_additive: true,
      },
      {
        id: 30,
        tier: 'stretch',
        title: 'Calling',
        target: 1,
        target_unit: 'job',
        frequency: 5,
        frequency_unit: 'per_week',
        is_additive: true,
      },
    ],
  },
];
