"""initial schema

Revision ID: 145d340640ce
Revises:
Create Date: 2026-04-12 21:44:00.878228

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy import Integer, String
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "145d340640ce"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coursestage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subtitle", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stage_number", sa.Integer(), nullable=False),
        sa.Column("overview_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("aspect", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("spiral_dynamics_color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("growing_up_stage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("divine_gender_polarity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("relationship_to_free_will", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("free_will_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "loginattempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loginattempt_email"), "loginattempt", ["email"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offering_balance", sa.Integer(), nullable=False),
        sa.Column("monthly_messages_used", sa.Integer(), nullable=False),
        sa.Column("monthly_reset_date", sa.DateTime(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "goalgroup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("shared_template", sa.Boolean(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "habit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("energy_cost", sa.Integer(), nullable=False),
        sa.Column("energy_return", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notification_times", postgresql.ARRAY(String()), nullable=True),
        sa.Column(
            "notification_frequency", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column("notification_days", postgresql.ARRAY(String()), nullable=True),
        sa.Column("milestone_notifications", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("streak", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "practice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stage_number", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
        sa.Column("default_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("submitted_by_user_id", sa.Integer(), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promptresponse",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stagecontent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_stage_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("release_day", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_stage_id"],
            ["coursestage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stageprogress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("current_stage", sa.Integer(), nullable=False),
        sa.Column("completed_stages", postgresql.ARRAY(Integer()), nullable=False),
        sa.Column("stage_started_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "contentcompletion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["stagecontent.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contentcompletion_content_id"), "contentcompletion", ["content_id"], unique=False
    )
    op.create_index(
        op.f("ix_contentcompletion_user_id"), "contentcompletion", ["user_id"], unique=False
    )
    op.create_table(
        "goal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("habit_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("tier", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("target_unit", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=False),
        sa.Column("frequency_unit", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("days_of_week", postgresql.ARRAY(String()), nullable=True),
        sa.Column("track_with_timer", sa.Boolean(), nullable=False),
        sa.Column("timer_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("goal_group_id", sa.Integer(), nullable=True),
        sa.Column("is_additive", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_group_id"],
            ["goalgroup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "userpractice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("practice_id", sa.Integer(), nullable=False),
        sa.Column("stage_number", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goalcompletion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("completed_units", sa.Float(), nullable=False),
        sa.Column("via_timer", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "practicesession",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_practice_id", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("reflection", sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_practice_id"],
            ["userpractice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "journalentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tag", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("practice_session_id", sa.Integer(), nullable=True),
        sa.Column("user_practice_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["practice_session_id"],
            ["practicesession.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_practice_id"],
            ["userpractice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llmusagelog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("journal_entry_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journalentry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llmusagelog_journal_entry_id"), "llmusagelog", ["journal_entry_id"], unique=False
    )
    op.create_index(op.f("ix_llmusagelog_model"), "llmusagelog", ["model"], unique=False)
    op.create_index(op.f("ix_llmusagelog_provider"), "llmusagelog", ["provider"], unique=False)
    op.create_index(op.f("ix_llmusagelog_timestamp"), "llmusagelog", ["timestamp"], unique=False)
    op.create_index(op.f("ix_llmusagelog_user_id"), "llmusagelog", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llmusagelog_user_id"), table_name="llmusagelog")
    op.drop_index(op.f("ix_llmusagelog_timestamp"), table_name="llmusagelog")
    op.drop_index(op.f("ix_llmusagelog_provider"), table_name="llmusagelog")
    op.drop_index(op.f("ix_llmusagelog_model"), table_name="llmusagelog")
    op.drop_index(op.f("ix_llmusagelog_journal_entry_id"), table_name="llmusagelog")
    op.drop_table("llmusagelog")
    op.drop_table("journalentry")
    op.drop_table("practicesession")
    op.drop_table("goalcompletion")
    op.drop_table("userpractice")
    op.drop_table("goal")
    op.drop_index(op.f("ix_contentcompletion_user_id"), table_name="contentcompletion")
    op.drop_index(op.f("ix_contentcompletion_content_id"), table_name="contentcompletion")
    op.drop_table("contentcompletion")
    op.drop_table("stageprogress")
    op.drop_table("stagecontent")
    op.drop_table("promptresponse")
    op.drop_table("practice")
    op.drop_table("habit")
    op.drop_table("goalgroup")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_loginattempt_email"), table_name="loginattempt")
    op.drop_table("loginattempt")
    op.drop_table("coursestage")
    # ### end Alembic commands ###
