name: Frontend CI

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/frontend-ci.yml"
      - ".pre-commit-config.yaml"
  pull_request:
    paths:
      - "app/**"
      - ".github/workflows/frontend-ci.yml"
      - ".pre-commit-config.yaml"

jobs:
  frontend-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "app/.nvmrc"
          cache: "npm"
          cache-dependency-path: "app/package.json"

      - name: Install dependencies
        working-directory: app
        run: npm ci || npm install

      - name: Lint
        working-directory: app
        run: npx eslint . --max-warnings=0

      - name: Type-check
        working-directory: app
        run: npx tsc -p tsconfig.json --noEmit

      - name: Format check
        working-directory: app
        run: npx prettier -c .

      - name: Tests
        working-directory: app
        run: npx jest --passWithNoTests
